### ISSUE TITLE
Rocky Linux 8.10 OOM not reqcognized

### ISSUE THREAD

**Issue by danci1973** [LukeShirnia/out-of-memory#28]
I'm attaching two examples of 'OOM' from a Rocky Linux 8.10 machine - since I'm useless with Python and programming overall, I can only humbly ask ('pretty please') to add support for these:

[oom1.txt](https://github.com/user-attachments/files/17248080/oom1.txt)
[oom2.txt](https://github.com/user-attachments/files/17248081/oom2.txt)

**Comment by LukeShirnia** [comment]
Hey @danci1973, thanks for raising the issue, and for the logs! Sorry for the delayed response. I've gone ahead and updated the script, it should now work. Let me know if you have any more issues.

**Comment by danci1973** [comment]
> Hey @danci1973, thanks for raising the issue, and for the logs! Sorry for the delayed response. I've gone ahead and updated the script, it should now work. Let me know if you have any more issues.

Thank you very much, much appreciated and quite useful tool.

I did find two more issues - one is, it doesn't work with 'dmesg' (-d) and causes this error:
```
Traceback (most recent call last):
  File "/usr/local/sbin/oom_investigate.py", line 1026, in <module>
    main()
  File "/usr/local/sbin/oom_investigate.py", line 1022, in main
    return run(system, options)
  File "/usr/local/sbin/oom_investigate.py", line 795, in run
    oom_lines.extend(analyzer.print_pretty_oom_instance(oom_instance))
  File "/usr/local/sbin/oom_investigate.py", line 637, in print_pretty_oom_instance
    + self._ok(oom_instance["start_time"].strftime("%a %b %d %X"))
AttributeError: 'NoneType' object has no attribute 'strftime'
```

And sometimes, working with '/var/log/messages' it reports completely wrong System RAM value:
```
# oom_investigate.py -f messages.txt -s 1 -r
________________________________________
      _____ _____ _____
     |     |     |     |
     |  |  |  |  | | | |
     |_____|_____|_|_|_|
     Out Of Memory Analyzer

© 2024 LukeShirnia

Disclaimer:
If the system OOMs too viciously, there may be nothing logged!
Do NOT take this script as FACT, ALWAYS investigate further.
________________________________________

OS: Rocky Linux 8.10
Python Version: 3.6.8
RAM: 6.05 GiB
Default System Log: /var/log/messages

Using Log File: messages.txt
Log Start Time: Sat Nov 03 03:14:12
Log End Time: Sat Nov 03 03:14:12

________________________________________


WARNING: This device has run out of memory at least once in this log file.

________________________________________

      Incident Overview
________________________________________

OOM Incidents: 5
Killed Services across all incidents:
- cache-main: killed 5 times

Highest OOM Incident: Incident Number 3
System Ram: 6,655 MB
Memory Used In Incident: 5845 MB

________________________________________

________________________________________

      Largest Incident
________________________________________

The largest OOM incident in this log file was:

OOM Incident: 3
Start Time: Sun Nov 04 18:32:26
System RAM: 6,655 MB
Total RAM at Incident: 5,845 MB
The following processes were killed:
  cache-main
Processes (showing top 10 processes):
  PROCESS       COUNT RSS (MB)
  cache-main       1  5,383 MB
  nginx            5  147 MB
  systemd-journal  1  106 MB
  varnishncsa      1  80 MB
  grep             2  35 MB
  fail2ban-server  1  21 MB
  rsyslogd         1  20 MB
  tuned            1  15 MB
  (sd-pam)         2  8 MB
  polkitd          1  6 MB

________________________________________

         OOM Incidents
________________________________________

Displaying 1 OOM incidents:

OOM Incident: 5
Start Time: Wed Nov 07 04:30:32
System RAM: 6.05 MB  <----------------------------------------------- wrong
Total RAM at Incident: 5,744 MB
The following processes were killed:
  cache-main
Processes (showing top 10 processes):
  PROCESS       COUNT  RSS (MB)
  cache-main       1   5,352 MB
  nginx            5   146 MB
  systemd-journal  1   88 MB
  varnishncsa      1   80 MB
  fail2ban-server  1   21 MB
  tuned            1   15 MB
  rsyslogd         1   14 MB
  polkitd          1   6 MB
  varnishd         1   6 MB
  snmpd            1   4 MB

________________________________________


(To increase the number of OOM incidents displayed, use the -s flag)
```
  
However, if I isolate just the last OOM incident in a separate file and process that file, the value is correct.
```
# oom_investigate.py -f oom-messages.txt -s 1 -r
  ________________________________________
      _____ _____ _____
     |     |     |     |
     |  |  |  |  | | | |
     |_____|_____|_|_|_|
     Out Of Memory Analyzer

© 2024 LukeShirnia

Disclaimer:
If the system OOMs too viciously, there may be nothing logged!
Do NOT take this script as FACT, ALWAYS investigate further.
________________________________________

OS: Rocky Linux 8.10
Python Version: 3.6.8
RAM: 6.05 GiB
Default System Log: /var/log/messages

Using Log File: oom-messages.txt
Log Start Time: Wed Nov 07 00:00:09
Log End Time: Wed Nov 07 00:00:09

________________________________________


WARNING: This device has run out of memory at least once in this log file.

________________________________________

      Incident Overview
________________________________________

OOM Incidents: 1
Killed Services across all incidents:
- cache-main: killed 1 times

Highest OOM Incident: Incident Number 1
System Ram: 6655 MB  <----------------------------------------------- correct
Memory Used In Incident: 5744 MB

________________________________________

         OOM Incidents
________________________________________

Displaying 1 OOM incidents:

OOM Incident: 1
Start Time: Wed Nov 07 04:30:32
System RAM: 6655 MB
Total RAM at Incident: 5,744 MB
The following processes were killed:
  cache-main
Processes (showing top 10 processes):
  PROCESS       COUNT  RSS (MB)
  cache-main       1   5,352 MB
  nginx            5   146 MB
  systemd-journal  1   88 MB
  varnishncsa      1   80 MB
  fail2ban-server  1   21 MB
  tuned            1   15 MB
  rsyslogd         1   14 MB
  polkitd          1   6 MB
  varnishd         1   6 MB
  snmpd            1   4 MB

________________________________________

```

I'm attaching all 3 examples (dmesg.txt, oom-messages.txt - just the last OOM incident, messages.txt - multiple incidents).
  
[oom-messages.txt](https://github.com/user-attachments/files/17657644/oom-messages.txt)
[dmesg.txt](https://github.com/user-attachments/files/17657641/dmesg.txt)
[messages.txt](https://github.com/user-attachments/files/17657642/messages.txt)

**Comment by LukeShirnia** [comment]
Thank you for reporting these! Sorry about the bugs. I've pushed a quick fix for the dmesg issue, you can find the script here https://github.com/LukeShirnia/out-of-memory/blob/fixes/oom_investigate.py. I'll test a bit more before merging into master.
I'll take a look at the system ram issue soon.

**Comment by LukeShirnia** [comment]
Hey @danci1973, I think the issues should be fixed. It's been merged into the main script now. Give me a shout if you have any more issues. Thanks again!
